import QtQuick 2.14

QtObject {
    readonly property color window: "#0f141b"
    readonly property color windowAccent: "#222b36"
    readonly property color surface: "#171d25"
    readonly property color surfaceOverlay: "#B8171D25"
    readonly property color section: "#1e2631"
    readonly property color sectionOverlay: "#A61E2631"
    readonly property color canvas: "#070d12"
    readonly property color border: "#334155"
    readonly property color borderOverlay: "#99334155"
    readonly property color text: "#e6edf3"
    readonly property color subtleText: "#97a3b6"
    readonly property color inverseText: "#f8fafc"
    readonly property color highlightSoft: "#182b45"
    readonly property color highlightText: "#7cb4ff"
    readonly property color highlightFill: "#2563eb"
    readonly property color successSoft: "#14271f"
    readonly property color successBorder: "#2f8a67"
    readonly property color successText: "#7ee2b7"
    readonly property color successFill: "#3fb950"
    readonly property color warningSoft: "#312813"
    readonly property color warningBorder: "#8a6a1f"
    readonly property color warningText: "#d29922"
    readonly property color warningFill: "#b7791f"
    readonly property color infoSoft: "#182b45"
    readonly property color infoBorder: "#3b82f6"
    readonly property color infoText: "#A8C7FA"
    readonly property color neutralSoft: "#202a36"
    readonly property color neutralBorder: "#475569"
    readonly property color neutralText: "#cbd5e1"
    readonly property color dangerSoft: "#2b1a21"
    readonly property color dangerBorder: "#b46076"
    readonly property color dangerText: "#ff9eb2"
    readonly property color dangerFill: "#f85149"
    readonly property color scrim: "#000000"
    readonly property color glow: "#173056"
    readonly property color secondaryGlow: "#121d2b"
}
